#!/bin/sh
# Sunszonecsv_test1 - for program SUNSZONECSV
# Author: Andre Latour, Sept 2024
#
  echo "----------------------------------------------------------------------------"
  echo "---  Input fake traces, apply shift.                                        "
  echo "---  The l2scrookred4 file has different names for the columns.             "
  echo "---  This test also uses layer 4 in the qin file (names 3 thicks, 4 vels)   "
  echo "---  This allows testing of the parameters which specify the names.         "
  echo "----------------------------------------------------------------------------"
#
# Note suchw does not honour scalco or scalel. So sdepth 120 means 12 for these headers.
#
  suchw <fake04.su >fake41.su key1=gelev,sdepth key2=selev,sdepth key3=selev,sdepth a=0,120
#
  sunszonecsv <fake41.su >fake42.su              locs=0 tpath=0 tapp=1 apply=1 \
              xys=skkx,sandrey thicks=zbbw_true,zkkb_true,yyzc_true \
              vels=vaw,vnqb,vwwwc,vddd \
              qin=l2scrookred4.csv
#
  sugethw <fake42.su key=sx,sy,selev,sdepth,gx,gy,gelev,offset,sstat,gstat,tstat,sec >fake42.txt
#
  suxwigb <fake42.su title=" after shift " &
#
